apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-service-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/punithbrave/go-service-2.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true